services:
  frontend:
    image: mikaelismail1/todos:frontend-v1
    ports:
      - 8080:80
  backend:
    build: ./backend/
#    image: mikaelismail1/todos:backend-v1
    volumes:
      - ./backend/todo.json:/var/www/html/api/todo.json
    env_file:
      - backend/.env
    ports:
      - 3000:80
  database:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "todos"
    command: --default-authentication-plugin=mysql_native_password